baseURL: "https://hansalshah007.github.io/portfolio/"
languageCode: "en-us"
title: "Portfolio - Hansal Shah"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     title: Blog posts
  #     url: /blogs
  #     weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio - Hansal Shah"
  description: This is where you get to know about me.
  staticPath: "/portfolio"  # The path to serve the static files from
  favicon: "/portfolio/images/hansal.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/portfolio/images/portfolio.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: true # Show brand logo in nav bar | default is true
    brandName: "Portfolio" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Hansal Shah."
    subtitle: "Transforming data into wisdom."
    content: "Graduate CS @ Cornell University"
    image: /portfolio/images/hansal.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume 🔗"
      url: "/portfolio/resume.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/HansalShah007/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/hansalms/
      customIcons:
        - icon: /portfolio/leetcode.svg
          url: "https://leetcode.com/hansal007/"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/portfolio/images/survivorship-bias.png"
    content: |-
      I am a  ***Machine Learning Engineer*** with a passion for developing software solutions. I have a background in computer science and mathematics, and I have a strong interest in Generative AI & Natural Language Processing. I am currently a graduate student at [Cornell](https://www.cornell.edu/) in Ithaca, NY. 

      I am currently working on a RAG-based chatbot that will be used to provide vertical search results in the domain knowledge of a specific expert.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Open Source LLMs"
        - "Langchain"
        - "PEFT - Huggingface models (LoRA/ QLoRA)"
        - "Retreival Augmented Generation"
        - "Pinecone"
        - "React"
        - "Fast APIs"
        - "Python"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Data Scientist Intern"
        company: "Reunion"
        companyUrl: "https://reunionhq.in/"
        date: "Dec 2022 - June 2023"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |
          - Managed data processing enhancements for real estate legal sales, handling complex JSONs and legal PDFs.
          - Collaborated with the team to create an ELT Data Pipeline on Databricks using Python, DBT, Spark-SQL, and Elastic Search.
          - Improved quantitative analytics and standardized real estate data using technologies like Delta Lakehouse Architecture and GPT.

      - job: "Software Developer Intern"
        company: "DEED Mobility Solutions"
        companyUrl: "https://iic.pdeu.ac.in/pdeu_startup/deed-mobility-solutions/"
        date: "May 2022 - August 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Led the development of a full-stack web application using ReactJS, enhancing business operations and user interaction
          - Implemented an IoT-based feature in the application for real-time EV tracking on Google Maps, improving customer experience and vehicle management.
          - Collaborated on back-end development with NodeJS, ExpressJS, and MongoDB, contributing to a more efficient and scalable system.

      - job: "MLE Intern"
        company: "BISAG"
        companyUrl: "https://bisag-n.gov.in/"
        date: "May 2022 - Aug 2022"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I interned as a Machine Learning Engineer at BISAG-N. 
          - Worked on extracting roads and paths from satellite imagery for military mapping purposes.
          - Implemented an image segmentation solution with the U-Net model using Tensorflow & Keras.
          - Achieved an Intersection over Union (IoU) score of 0.7, successfully enhancing military capabilities in mapping unknown regions.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Engineering in Computer Science"
        school:
          name: "Cornell University"
          url: "https://www.cornell.edu/"
        date: "2023 - 2024"
        GPA: "4.14 out of 4.3"
        content: |-
          Extracurricular Activities
            - Teaching Assistant - Designing Data Products (NBA 6070) 
            - Teaching Assistant - Machine Learning (CS 5780)
      - title: "Bachelor of Technology in Computer Science & Engineering"
        school:
          name: "Pandit Deendayal Energy University"
          url: "https://www.pdpu.ac.in/"
        date: "2019 - 2023"
        GPA: "4.0 out of 4.0"
        content: |-
          Published four research papers in various journals and conferences:
          - [Cardiovascular disease prediction using various machine learning algorithms 🔗](https://research.skylineuniversity.ac.ae/id/eprint/584/1/Cardiovascular%20Disease%20Prediction%20using%20Various%20Machine%20Learning%20Algorithms..pdf)
          - [Enhanced handwritten digit recognition using optimally selected optimizer for an ANN 🔗](https://link.springer.com/article/10.1007/s11042-023-15402-0)
          - [Hand Gesture to Character Recognition using Convolutional Neural Network 🔗](https://ieeexplore.ieee.org/abstract/document/10053103)
          - [Integrated Database Management System for Emergency Services 🔗](https://ieeexplore.ieee.org/abstract/document/9670946)

          Extracurricular Activities
            - President of Brahmand - The Astronomy Club of PDEU
              - Led a diverse team of 54 members across 6 departments.
              - Planned and coordinated monthly events.
              - Briefed department heads on their roles and event contributions.
              - Oversaw financial and technical decisions made by the Treasurer, Vice President, and General Secretary.
              - Acted as a mediator to resolve conflicts and ensure smooth operations.
            
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://drive.google.com/file/d/1Qkj0KElMWv01ygQ8xKih9pj82c7f5BHQ/view?usp=sharing"
      


  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Academic Gold Medalist
        content: First Merit Rank - B.Tech CSE
        image: /portfolio/images/medal.jpg
      - title: DBT - Open Source Contributor
        content: Contributed to a open source ETL tool (DBT) 🔗
        url: https://github.com/dbt-labs/dbt-core/issues/7138
        image: /portfolio/images/dbt.png

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: R2Decide - Chatbot
        content: Leading the creation of a Retrieval-Augmented Generation system with a fine-tuned LLAMA 2 model for personalized, expert responses.
        image: /portfolio/images/projects/r2decide.jpg
        featured:
          name: Discord Bot (Alpha Version)
          link: https://discord.com/invite/6KEPb7KH
        badges:
          - "RAG"
          - "PEFT"
          - "NLP"
          - "Python"
          - "Pinecone"
        # links:
        #   - icon: fa fa-discord
        #     url: https://discord.com/invite/6KEPb7KH
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Readme.md File Generator
        content: Readme.md generator is a React application that takes basic information about the user's project as an input and generates a README file which the user can upload directly in their project's repository.
        image: /portfolio/images/projects/readme.png
        featured:
          name: Website
          link: https://hansalshah007.github.io/readme-generator/
        badges:
          - "React"
          - "Node"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/HansalShah007/readme-generator

      - title: OS Virtual Lab
        content: A web application that represents and runs different algorithms that Operating Systems use to run the computers. The application provides graphs for visualization, generates PDFs for explaining the math involved in calculations, and provides a way to compare the performance of different Disk Scheduling algorithms.
        image: /portfolio/images/projects/osvirtuallab.png
        featured:
          name: Website
          link: https://hansalshah007.github.io/osvirtuallab/
        badges:
          - "HTML"
          - "CSS"
          - "Javascript"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/HansalShah007/osvirtuallab

      - title: Tic-Tac-Toe
        content: A web application provides a simple implementation of the popular game Tic-Tac-Toe. Here, you play against the computer and you have the freedom to make the first move and pick your playing symbol. The game implements the Mini-Max algorithm for the computer to choose an optimal move after you make your move. I dare you to win against the computer.
        image: /portfolio/images/projects/tictactoe.png
        featured:
          name: Website
          link: https://hansalshah007.github.io/Tic-Tac-Toe-MiniMax/
        badges:
          - "AI (Mini-Max)"  
          - "HTML"
          - "CSS"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/HansalShah007/Tic-Tac-Toe-MiniMax

      - title: EV-Navigator
        content: A method for predicting the State of Charge (SOC), the State of Energy (SOE), and ultimately the range prediction using a sequence of neural network models. The technique predicts the range of the vehicle by taking into account the state of the battery, the state of the vehicle, the driving style, and the road conditions. The system is deployed as a website to visualize it's working in real life.
        image: /portfolio/images/projects/evnavigator.png
        featured:
          name: Website
          link: https://hansalshah007.github.io/EV-Navigator/index.html
        badges:
          - "Tensorflow"  
          - "Keras"
          - "ANNs"
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/HansalShah007/EV-Navigator

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: hms262@cornell.edu
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/HansalShah007/
      linkedin: https://www.linkedin.com/in/hansalms/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
